spring.application.name=kanbanBoard

spring.datasource.url=jdbc:mysql://localhost:3306/board?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.flyway.enabled=true

#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
logging.level.org.springframework.security=DEBUG